import React from "react";
import "./App.css";
import Card from "./components/Card";
import AddCardButton from "./components/AddCardButton";

function App() {
  const [cards, setCards] = React.useState([]);

  const [testimonials, setTestimonials] = React.useState([
    `I've worked with Lovro for over 2 years, and he has always been a great asset to my team.`,
    `Lovro’ s coding skills are second-to-none, and he's always creating new ideas and solutions that help me get the most out of my projects.`,
    `I would highly recommend him for anyone looking for a talented frontend developer!`,
    `Lovro has been my go-to frontend developer for the past year.`,
    `I've tried a bunch of other frontend devs and none of them can hold a candle to him.`,
    `He takes on any challenge, no matter how long it takes, and his work is always top notch and up to date with the latest best practices.`,
    `His eagerness and passion are unmatched.`,
    `I've been working with Lovro for 2 years now, I can highly recommend him!`,
    `He is the best frontend developer I have ever met!`,
    `He always knows how to find a solution even when the problem seems unsolvable.`,
    `His skills of UX and UI are stronger than any other developers I know.`,
    `Lovro is simply the best frontend developer in the market.`,
    `I've worked with a few developers before and Lovro is the only one who has such a keen eye for design and UX.`,
    `His work quality is top-notch!`,
    `Lovro has a great grasp on frontend development and is always willing to share his knowledge with everyone else in the team.`,
    `He always takes responsibility for any bug or malfunction in the application and never blames anyone else.`,
    `He has always been the first one to come up with the best solution, no matter how obscure the problem is.`,
    `I often call him my secret weapon because many of our clients love him so much that they want to hire him fulltime.`,
    `I can't say enough about Lovro. He is hands down the best Frontend developer I've had the pleasure of working with.`,
    `His attention to detail and ability to adapt to any style is unparalleled.`,
    `I have been working with Lovro for 3 years now and he is the best front-end developer I have ever had!`,
    `His work is always neat, clean, & well documented which makes it easy for me to manage my projects.`,
    `Lovro is a great front-end developer and has been a reliable teammate for the past 2 years.`,
    `He is always calm, collected, and happy which helps us get through the long hours with some laughs and good conversation.`,
    `Lovro is one of the most valuable people on my team because he can do so many things without hesitation.`,
    `He's great at solving problems and writing clean code.`,
    `I've been working with Lovro for the past few months on a front-end project and I must say that I'm impressed.`,
    `He is one of the most talented UI designers in his field and is excellent at what he does.`,
    `He has an amazing eye for detail, a great sense of humor and always makes work fun!`,
    `I'm Lovro’ s customer for 2 years now and he never let me down!`,
    `He is always on time, communicates well and delivers what I need.`,
    `I really recommend him for any project you have in your mind (and budget). You will not be disappointed!`,
    `We were in need for a front-end developer and found Lovro on LinkedIn. We were really impressed with his portfolio, quality of his code, and commitment to deadlines.`,
    `He's been with our team for 2 years now, during that time I've seen him grow through the ranks to become one of the best front-end developers out there.`,
    `Lovro is an awesome developer, he was the only one who could help me with my project.`,
    `He never complained about the extra work and even offered to help out on some other projects as well.`,
    `He is the best frontend developer I have come across in this industry.`,
    `His knowledge, expertise and creativity are unparalleled.`,
    `He is never late and delivers a superb product every single time.`,
    `I have been working with Lovro for over 2 years now and he is the best frontend developer I have come across!`,
    `He is super passionate and knowledgeable about his work.`,
    `His skills are matched by his efficiency, always meeting deadlines without fail.`,
    `If you need to hire a frontend developer, make it Lovro!`,
  ]);

  const firstNames = [
    "Addison",
    "Andy",
    "Finley",
    "Finn",
    "Florian",
    "Flynn",
    "Francis",
    "Frankie",
    "Gabriel",
    "Gene",
    "Genesis",
    "George",
    "Angel",
    "Glen",
    "Grey",
    "Hadley",
    "Harley",
    "Harlow",
    "Harper",
    "Haven",
    "Hayden",
    "Henry",
    "Honour",
    "Archer",
    "Hudson",
    "Hunter",
    "Indigo",
    "Jack",
    "Jackie",
    "Jade",
    "Jaden",
    "James",
    "Jamie",
    "Jan",
    "Arden",
    "Jayden",
    "Jean",
    "Jesse",
    "Jessie",
    "Jody",
    "Jordan",
    "Jude",
    "Jules",
    "Julian",
    "Kaden",
    "Ari",
    "Kai",
    "Kameron",
    "Keegan",
    "Keely",
    "Kelly",
    "Kelsey",
    "Kendall",
    "Kennedy",
    "Kerry",
    "Kim",
    "Ariel",
    "Kit",
    "Kylar",
    "Kyle",
    "Kylin",
    "Kyrie",
    "Lake",
    "Landon",
    "Lane",
    "Leah",
    "Lee",
    "Armani",
    "Leighton",
    "Lennon",
    "Lennox",
    "Leslie",
    "Lincoln",
    "Linden",
    "Lindsay",
    "Logan",
    "London",
    "Lonnie",
    "Arya",
    "Loren",
    "Lou",
    "Mackenzie",
    "Maddox",
    "Madison",
    "Marley",
    "Marlow",
    "Mason",
    "Max",
    "Maxwell",
    "Ash",
    "Mckenna",
    "Mckenzie",
    "Micah",
    "Michael",
    "Milan",
    "Miller",
    "Monroe",
    "Montana",
    "Morgan",
    "Murphy",
    "Ashley",
    "Nevada",
    "Nicky",
    "Nico",
    "Nikita",
    "Noel",
    "Noelle",
    "Nolan",
    "Nova",
    "Ocean",
    "Owen",
    "Adrian",
    "Ashton",
    "Paige",
    "Paisley",
    "Paris",
    "Parker",
    "Pat",
    "Payton",
    "Peace",
    "Perry",
    "Peyton",
    "Phoenix",
    "Aspen",
    "Piper",
    "Poet",
    "Quincy",
    "Quinn",
    "Raleigh",
    "Ramsey",
    "Raphael",
    "Ray",
    "Rayne",
    "Reagan",
    "Athena",
    "Reed",
    "Reese",
    "Regan",
    "Remi",
    "Remington",
    "Remy",
    "Rene",
    "Riley",
    "Rio",
    "Ripley",
    "Aubrey",
    "River",
    "Roan",
    "Robin",
    "Robyn",
    "Rory",
    "Rowan",
    "Royal",
    "Ryan",
    "Ryder",
    "Rylan",
    "Auden",
    "Sage",
    "Sailor",
    "Salem",
    "Sam",
    "Sasha",
    "Sawyer",
    "Sean",
    "Shae",
    "Shannon",
    "Shawn",
    "August",
    "Shay",
    "Shiloh",
    "Sidney",
    "Skye",
    "Skylar",
    "Sloane",
    "Spencer",
    "Sterling",
    "Stevie",
    "Storm",
    "Avery",
    "Sunny",
    "Sutton",
    "Sydney",
    "Tanner",
    "Tate",
    "Tatum",
    "Taylor",
    "Teagan",
    "Tennessee",
    "Tennyson",
    "Avis",
    "Teri",
    "Terry",
    "Tiernan",
    "Tobin",
    "Toby",
    "Toni",
    "Tony",
    "Tori",
    "Tracy",
    "Trinity",
    "Bailey",
    "Tristan",
    "TRUE",
    "Tyler",
    "Umber",
    "Val",
    "Valentine",
    "Venice",
    "Vick",
    "Wallace",
    "Wesley",
    "Baker",
    "West",
    "Weston",
    "Whitney",
    "Wilder",
    "Windsor",
    "Wynn",
    "Winter",
    "Wisdom",
    "Wren",
    "Wyatt",
    "Aiden",
    "Bay",
    "Zephyr",
    "Bellamy",
    "Bergen",
    "Bevan",
    "Billie",
    "Billy",
    "Blaine",
    "Blair",
    "Blake",
    "Blue",
    "Ainsley",
    "Bobby",
    "Bowie",
    "Brady",
    "Brennan",
    "Brent",
    "Brett",
    "Briar",
    "Brighton",
    "Britton",
    "Brooke",
    "Alex",
    "Brooklyn",
    "Brooks",
    "Caelan",
    "Cameron",
    "Campbell",
    "Carey",
    "Carmel",
    "Carmen",
    "Carroll",
    "Carson",
    "Alfie",
    "Carter",
    "Casey",
    "Cassidy",
    "Chance",
    "Channing",
    "Charley",
    "Charlie",
    "Chris",
    "Clay",
    "Clayton",
    "Ali",
    "Cody",
    "Cole",
    "Corey",
    "Dakota",
    "Dale",
    "Dallas",
    "Dana",
    "Dane",
    "Darby",
    "Daryl",
    "Amory",
    "Dawson",
    "Delta",
    "Denver",
    "Devin",
    "Dorian",
    "Drew",
    "Dylan",
    "Easton",
    "Eddie",
    "Eden",
    "Andie",
    "Elliott",
    "Ellis",
    "Ellison",
    "Ember",
    "Emerson",
    "Emery",
    "Emory",
    "Erin",
    "Evelyn",
    "Ezra",
  ];
  const lastNames = [
    "Adams",
    "Barnes",
    "Roberts",
    "Robertson",
    "Robinson",
    "Rogers",
    "Rose",
    "Ross",
    "Russell",
    "Saunders",
    "Scott",
    "Shaw",
    "Bell",
    "Simpson",
    "Smith",
    "Spencer",
    "Stevens",
    "Stewart",
    "Taylor",
    "Thomas",
    "Thompson",
    "Thomson",
    "Turner",
    "Bennett",
    "Walker",
    "Walsh",
    "Ward",
    "Watson",
    "Watts",
    "Webb",
    "Webster",
    "West",
    "White",
    "Wilkinson",
    "Booth",
    "Williams",
    "Williamson",
    "Wilson",
    "Wood",
    "Wright",
    "Young",
    "Bradley",
    "Brooks",
    "Brown",
    "Burton",
    "Butler",
    "Campbell",
    "Allen",
    "Carter",
    "Chapman",
    "Clarke",
    "Cole",
    "Collins",
    "Cook",
    "Cooper",
    "Corbyn",
    "Cox",
    "Davidson",
    "Anderson",
    "Davies",
    "Dawson",
    "Dixon",
    "Edwards",
    "Elliott",
    "Evans",
    "Fisher",
    "Fletcher",
    "Ford",
    "Foster",
    "Armstrong",
    "Fox",
    "Gibson",
    "Graham",
    "Grant",
    "Gray",
    "Green",
    "Griffiths",
    "Hall",
    "Hamilton",
    "Harris",
    "Atkinson",
    "Harrison",
    "Harvey",
    "Henderson",
    "Hill",
    "Holmes",
    "Howard",
    "Hughes",
    "Hunt",
    "Hunter",
    "Jackson",
    "Bailey",
    "James",
    "Jenkins",
    "Johnson",
    "Johnston",
    "Jones",
    "Kelly",
    "Kennedy",
    "King",
    "Knight",
    "Lawrence",
    "Baker",
    "Lee",
    "Lewis",
    "Lloyd",
    "Marshall",
    "Martin",
    "Mason",
    "Matthews",
    "McDonald",
    "Miller",
    "Mitchell",
    "Ball",
    "Moore",
    "Morgan",
    "Morris",
    "Morrison",
    "Murphy",
    "Murray",
    "Owen",
    "Palmer",
    "Parker",
    "Payne",
    "Barker",
    "Pearce",
    "Pearson",
    "Perry",
    "Phillips",
    "Powell",
    "Price",
    "Reid",
    "Reynolds",
    "Richards",
    "Richardson",
  ];

  function addCard() {
    // construct a random first name and last name
    const newFirstName =
      firstNames[Math.floor(Math.random() * firstNames.length)];
    const newLastName = lastNames[Math.floor(Math.random() * lastNames.length)];

    // pick a random testimonial and delete it from the testimonial array, so it doesn't repeat
    const newTestimonialIndex = Math.floor(Math.random() * testimonials.length);
    const newTestimonial = testimonials[newTestimonialIndex];

    setTestimonials((prevTestimonials) =>
      [...prevTestimonials].filter(
        (_testimonial, index) => newTestimonialIndex !== index
      )
    );

    // generate new card info and add it to the cards array
    setCards((prevCards) => [
      ...prevCards,
      { name: `${newFirstName} ${newLastName}`, testimonial: newTestimonial },
    ]);
  }

  // create rendered Card components
  const renderCards = cards.map((card, index) => (
    <Card
      name={card.name}
      key={index}
      uniqueKey={index}
      testimonial={card.testimonial}
    />
  ));

  return (
    <div>
      <AddCardButton addCard={addCard} />
      <div className="cards-container">{renderCards}</div>
    </div>
  );
}

export default App;
